In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[271, 3483, 6399, 8060],
 [271, 3483, 6399, 3106],
 [271, 1792, 6399, 8818],
 [882, 4209, 6340, 1419, 4310],
 [882, 4209, 6340, 1419, 2457],
 [3374, 271, 2450, 6399, 482],
 [4512, 8860, 3761, 1419]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  271 3483 6399 8060]
 [   0    0    0    0  271 3483 6399 3106]
 [   0    0    0    0  271 1792 6399 8818]
 [   0    0    0  882 4209 6340 1419 4310]
 [   0    0    0  882 4209 6340 1419 2457]
 [   0    0    0 3374  271 2450 6399  482]
 [   0    0    0    0 4512 8860 3761 1419]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Aman Kumar\anaconda3\envs\tf-env\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step


array([[[ 8.06528330e-03,  4.43400182e-02, -3.19724828e-02,
         -3.05886623e-02,  4.21344675e-02, -9.64677334e-03,
         -1.99607853e-02, -1.92308314e-02, -3.96952629e-02,
          1.34309195e-02],
        [ 8.06528330e-03,  4.43400182e-02, -3.19724828e-02,
         -3.05886623e-02,  4.21344675e-02, -9.64677334e-03,
         -1.99607853e-02, -1.92308314e-02, -3.96952629e-02,
          1.34309195e-02],
        [ 8.06528330e-03,  4.43400182e-02, -3.19724828e-02,
         -3.05886623e-02,  4.21344675e-02, -9.64677334e-03,
         -1.99607853e-02, -1.92308314e-02, -3.96952629e-02,
          1.34309195e-02],
        [ 8.06528330e-03,  4.43400182e-02, -3.19724828e-02,
         -3.05886623e-02,  4.21344675e-02, -9.64677334e-03,
         -1.99607853e-02, -1.92308314e-02, -3.96952629e-02,
          1.34309195e-02],
        [ 2.03037895e-02, -4.73298915e-02, -3.36382277e-02,
         -4.66093682e-02, -3.29710469e-02, -4.65058461e-02,
          4.32867929e-03, -2.92536616e-02,  4.163873

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  271, 3483, 6399, 8060])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531